### ISSUE TITLE
Sunshine Streamer support

### ISSUE THREAD

**Issue by GodOfWar526** [hansschmucker/NVStreamer1080#14] opened 2022-12-31 21:25 UTC
With Nvidia pulling the plug on its game-streaming support in February I think it would be important to support its Open source alternative, Sunshine.

https://github.com/loki-47-6F-64/sunshine

I am not associated with the project, just a fan with an ultrawide that happens to use both because its highly convenient.

**Comment by hansschmucker** [comment] 2023-01-15 02:10
Hi GOW
Just installed Sunshine for the first time and I'm pretty impressed... it also looks to be a very compact replacement for GameStream that doesn't include too much out of the box, so I guess they're not going to implement resolution handling themselves.

I've just finished a first implementation and am going to test it during the week.

One thing to note: It will require admin access for NVStreamer. The problem is that there's no status endpoint I can check, so what I'm doing now is stopping the service (for which admin access is required), then spinning up a new instance of sunshine where I can scan STDOUT and STDERR for CLIENT CONNECTED,CLIENT DISCONNECTED.

Maybe Sunshine will get such an endpoint at some point, but for now this is the easiest way to do it.

**Comment by hansschmucker** [comment] 2023-01-15 21:05
[NVStreamer1080.zip](https://github.com/hansschmucker/NVStreamer1080/files/10421220/NVStreamer1080.zip)

If anybody wants to try the first attempt, here's the first attempt ^^

**Comment by hansschmucker** [comment] 2023-01-17 21:01
I've been trying it for a few days now... as I said, it requires admin rights, but other than that I consider it stable.... so I'm closing this issue and preparing the release ^^

**Closed by hansschmucker** 2023-01-17 21:01 UTC
